// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BSU_Engine_Gauge

#include "ui.h"

lv_obj_t * uic_btnNext1;
lv_obj_t * uic_btnBack1;
lv_obj_t * uic_txtGasFlowRate;
lv_obj_t * uic_arcGasFlowRate;
lv_obj_t * uic_txtLoadCell;
lv_obj_t * uic_arcLoadCell;
lv_obj_t * uic_txtEngineRpm1;
lv_obj_t * uic_arcEngineRpm1;
lv_obj_t * uic_txtPower;
lv_obj_t * uic_arcPower;
lv_obj_t * uic_txtAmpere;
lv_obj_t * uic_arcAmpere;
lv_obj_t * uic_txtVoltage;
lv_obj_t * uic_arcVoltage;
lv_obj_t * uic_srcGeneratorGauge;
lv_obj_t * ui_srcGeneratorGauge = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Gauge9 = NULL;
lv_obj_t * ui_arcVoltage = NULL;
lv_obj_t * ui_txtVoltage = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Gauge10 = NULL;
lv_obj_t * ui_arcAmpere = NULL;
lv_obj_t * ui_txtAmpere = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Gauge11 = NULL;
lv_obj_t * ui_arcPower = NULL;
lv_obj_t * ui_txtPower = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Gauge12 = NULL;
lv_obj_t * ui_arcEngineRpm1 = NULL;
lv_obj_t * ui_txtEngineRpm1 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Gauge14 = NULL;
lv_obj_t * ui_arcLoadCell = NULL;
lv_obj_t * ui_txtLoadCell = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Gauge15 = NULL;
lv_obj_t * ui_arcGasFlowRate = NULL;
lv_obj_t * ui_txtGasFlowRate = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_btnBack1 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_btnNext1 = NULL;
lv_obj_t * ui_Label28 = NULL;
// event funtions
void ui_event_btnBack1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_btnNext1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_srcEngineGauge, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_srcEngineGauge_screen_init);
    }
}

// build funtions

void ui_srcGeneratorGauge_screen_init(void)
{
    ui_srcGeneratorGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_srcGeneratorGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_srcGeneratorGauge);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 35);
    lv_obj_set_align(ui_Label18, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label18, "GENERATOR GAUGES");
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_srcGeneratorGauge);
    lv_img_set_src(ui_Image3, &ui_img_logo_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Image3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge9 = lv_obj_create(ui_srcGeneratorGauge);
    lv_obj_remove_style_all(ui_Gauge9);
    lv_obj_set_width(ui_Gauge9, 200);
    lv_obj_set_height(ui_Gauge9, 200);
    lv_obj_set_x(ui_Gauge9, -350);
    lv_obj_set_y(ui_Gauge9, -95);
    lv_obj_set_align(ui_Gauge9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge9, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge9, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge9, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge9, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcVoltage = lv_arc_create(ui_Gauge9);
    lv_obj_set_width(ui_arcVoltage, 135);
    lv_obj_set_height(ui_arcVoltage, 135);
    lv_obj_set_align(ui_arcVoltage, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcVoltage, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcVoltage, 50);
    lv_obj_set_style_arc_color(ui_arcVoltage, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcVoltage, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcVoltage, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtVoltage = lv_label_create(ui_Gauge9);
    lv_obj_set_width(ui_txtVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtVoltage, "220V");
    lv_obj_set_style_text_font(ui_txtVoltage, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Gauge9);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 1);
    lv_obj_set_y(ui_Label19, 61);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "VOLTAGE");
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge10 = lv_obj_create(ui_srcGeneratorGauge);
    lv_obj_remove_style_all(ui_Gauge10);
    lv_obj_set_width(ui_Gauge10, 200);
    lv_obj_set_height(ui_Gauge10, 200);
    lv_obj_set_x(ui_Gauge10, -120);
    lv_obj_set_y(ui_Gauge10, -95);
    lv_obj_set_align(ui_Gauge10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge10, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge10, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge10, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge10, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcAmpere = lv_arc_create(ui_Gauge10);
    lv_obj_set_width(ui_arcAmpere, 135);
    lv_obj_set_height(ui_arcAmpere, 135);
    lv_obj_set_align(ui_arcAmpere, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcAmpere, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcAmpere, 50);
    lv_obj_set_style_arc_color(ui_arcAmpere, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcAmpere, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcAmpere, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcAmpere, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtAmpere = lv_label_create(ui_Gauge10);
    lv_obj_set_width(ui_txtAmpere, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAmpere, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtAmpere, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAmpere, "20 A");
    lv_obj_set_style_text_font(ui_txtAmpere, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Gauge10);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 1);
    lv_obj_set_y(ui_Label20, 61);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "AMPERE");
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge11 = lv_obj_create(ui_srcGeneratorGauge);
    lv_obj_remove_style_all(ui_Gauge11);
    lv_obj_set_width(ui_Gauge11, 200);
    lv_obj_set_height(ui_Gauge11, 200);
    lv_obj_set_x(ui_Gauge11, 120);
    lv_obj_set_y(ui_Gauge11, -95);
    lv_obj_set_align(ui_Gauge11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge11, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge11, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge11, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge11, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcPower = lv_arc_create(ui_Gauge11);
    lv_obj_set_width(ui_arcPower, 135);
    lv_obj_set_height(ui_arcPower, 135);
    lv_obj_set_align(ui_arcPower, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcPower, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcPower, 50);
    lv_obj_set_style_arc_color(ui_arcPower, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcPower, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcPower, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtPower = lv_label_create(ui_Gauge11);
    lv_obj_set_width(ui_txtPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtPower, "100 w");
    lv_obj_set_style_text_font(ui_txtPower, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Gauge11);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 1);
    lv_obj_set_y(ui_Label21, 61);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "POWER");
    lv_obj_set_style_text_align(ui_Label21, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge12 = lv_obj_create(ui_srcGeneratorGauge);
    lv_obj_remove_style_all(ui_Gauge12);
    lv_obj_set_width(ui_Gauge12, 200);
    lv_obj_set_height(ui_Gauge12, 200);
    lv_obj_set_x(ui_Gauge12, 350);
    lv_obj_set_y(ui_Gauge12, -95);
    lv_obj_set_align(ui_Gauge12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge12, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge12, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge12, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcEngineRpm1 = lv_arc_create(ui_Gauge12);
    lv_obj_set_width(ui_arcEngineRpm1, 135);
    lv_obj_set_height(ui_arcEngineRpm1, 135);
    lv_obj_set_align(ui_arcEngineRpm1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcEngineRpm1, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcEngineRpm1, 50);
    lv_obj_set_style_arc_color(ui_arcEngineRpm1, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcEngineRpm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcEngineRpm1, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcEngineRpm1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtEngineRpm1 = lv_label_create(ui_Gauge12);
    lv_obj_set_width(ui_txtEngineRpm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtEngineRpm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtEngineRpm1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtEngineRpm1, "1500");
    lv_obj_set_style_text_font(ui_txtEngineRpm1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Gauge12);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 1);
    lv_obj_set_y(ui_Label22, 61);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "RPM");
    lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge14 = lv_obj_create(ui_srcGeneratorGauge);
    lv_obj_remove_style_all(ui_Gauge14);
    lv_obj_set_width(ui_Gauge14, 200);
    lv_obj_set_height(ui_Gauge14, 200);
    lv_obj_set_x(ui_Gauge14, -120);
    lv_obj_set_y(ui_Gauge14, 150);
    lv_obj_set_align(ui_Gauge14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge14, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge14, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge14, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge14, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcLoadCell = lv_arc_create(ui_Gauge14);
    lv_obj_set_width(ui_arcLoadCell, 135);
    lv_obj_set_height(ui_arcLoadCell, 135);
    lv_obj_set_align(ui_arcLoadCell, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcLoadCell, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcLoadCell, 50);
    lv_obj_set_style_arc_color(ui_arcLoadCell, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcLoadCell, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcLoadCell, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcLoadCell, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtLoadCell = lv_label_create(ui_Gauge14);
    lv_obj_set_width(ui_txtLoadCell, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtLoadCell, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtLoadCell, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtLoadCell, "50 C");
    lv_obj_set_style_text_font(ui_txtLoadCell, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Gauge14);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 1);
    lv_obj_set_y(ui_Label24, 61);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "LOAD CELL");
    lv_obj_set_style_text_align(ui_Label24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge15 = lv_obj_create(ui_srcGeneratorGauge);
    lv_obj_remove_style_all(ui_Gauge15);
    lv_obj_set_width(ui_Gauge15, 200);
    lv_obj_set_height(ui_Gauge15, 200);
    lv_obj_set_x(ui_Gauge15, 120);
    lv_obj_set_y(ui_Gauge15, 150);
    lv_obj_set_align(ui_Gauge15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge15, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge15, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge15, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge15, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcGasFlowRate = lv_arc_create(ui_Gauge15);
    lv_obj_set_width(ui_arcGasFlowRate, 135);
    lv_obj_set_height(ui_arcGasFlowRate, 135);
    lv_obj_set_align(ui_arcGasFlowRate, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcGasFlowRate, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcGasFlowRate, 50);
    lv_obj_set_style_arc_color(ui_arcGasFlowRate, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcGasFlowRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcGasFlowRate, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcGasFlowRate, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtGasFlowRate = lv_label_create(ui_Gauge15);
    lv_obj_set_width(ui_txtGasFlowRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtGasFlowRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtGasFlowRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtGasFlowRate, "4 L/S");
    lv_obj_set_style_text_font(ui_txtGasFlowRate, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Gauge15);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 1);
    lv_obj_set_y(ui_Label25, 61);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "FLOW RATE\nGAS");
    lv_obj_set_style_text_align(ui_Label25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack1 = lv_btn_create(ui_srcGeneratorGauge);
    lv_obj_set_width(ui_btnBack1, 180);
    lv_obj_set_height(ui_btnBack1, 60);
    lv_obj_set_x(ui_btnBack1, -400);
    lv_obj_set_y(ui_btnBack1, -250);
    lv_obj_set_align(ui_btnBack1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_btnBack1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "BACK");
    lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnNext1 = lv_btn_create(ui_srcGeneratorGauge);
    lv_obj_set_width(ui_btnNext1, 180);
    lv_obj_set_height(ui_btnNext1, 60);
    lv_obj_set_x(ui_btnNext1, 400);
    lv_obj_set_y(ui_btnNext1, -250);
    lv_obj_set_align(ui_btnNext1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnNext1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnNext1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_btnNext1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "NEXT");
    lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnBack1, ui_event_btnBack1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnNext1, ui_event_btnNext1, LV_EVENT_ALL, NULL);
    uic_srcGeneratorGauge = ui_srcGeneratorGauge;
    uic_arcVoltage = ui_arcVoltage;
    uic_txtVoltage = ui_txtVoltage;
    uic_arcAmpere = ui_arcAmpere;
    uic_txtAmpere = ui_txtAmpere;
    uic_arcPower = ui_arcPower;
    uic_txtPower = ui_txtPower;
    uic_arcEngineRpm1 = ui_arcEngineRpm1;
    uic_txtEngineRpm1 = ui_txtEngineRpm1;
    uic_arcLoadCell = ui_arcLoadCell;
    uic_txtLoadCell = ui_txtLoadCell;
    uic_arcGasFlowRate = ui_arcGasFlowRate;
    uic_txtGasFlowRate = ui_txtGasFlowRate;
    uic_btnBack1 = ui_btnBack1;
    uic_btnNext1 = ui_btnNext1;

}

void ui_srcGeneratorGauge_screen_destroy(void)
{
    if(ui_srcGeneratorGauge) lv_obj_del(ui_srcGeneratorGauge);

    // NULL screen variables
    uic_srcGeneratorGauge = NULL;
    ui_srcGeneratorGauge = NULL;
    ui_Label18 = NULL;
    ui_Image3 = NULL;
    ui_Gauge9 = NULL;
    uic_arcVoltage = NULL;
    ui_arcVoltage = NULL;
    uic_txtVoltage = NULL;
    ui_txtVoltage = NULL;
    ui_Label19 = NULL;
    ui_Gauge10 = NULL;
    uic_arcAmpere = NULL;
    ui_arcAmpere = NULL;
    uic_txtAmpere = NULL;
    ui_txtAmpere = NULL;
    ui_Label20 = NULL;
    ui_Gauge11 = NULL;
    uic_arcPower = NULL;
    ui_arcPower = NULL;
    uic_txtPower = NULL;
    ui_txtPower = NULL;
    ui_Label21 = NULL;
    ui_Gauge12 = NULL;
    uic_arcEngineRpm1 = NULL;
    ui_arcEngineRpm1 = NULL;
    uic_txtEngineRpm1 = NULL;
    ui_txtEngineRpm1 = NULL;
    ui_Label22 = NULL;
    ui_Gauge14 = NULL;
    uic_arcLoadCell = NULL;
    ui_arcLoadCell = NULL;
    uic_txtLoadCell = NULL;
    ui_txtLoadCell = NULL;
    ui_Label24 = NULL;
    ui_Gauge15 = NULL;
    uic_arcGasFlowRate = NULL;
    ui_arcGasFlowRate = NULL;
    uic_txtGasFlowRate = NULL;
    ui_txtGasFlowRate = NULL;
    ui_Label25 = NULL;
    uic_btnBack1 = NULL;
    ui_btnBack1 = NULL;
    ui_Label27 = NULL;
    uic_btnNext1 = NULL;
    ui_btnNext1 = NULL;
    ui_Label28 = NULL;

}
