// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BSU_Engine_Gauge

#ifndef UI_SRCENGINEGAUGE_H
#define UI_SRCENGINEGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_srcEngineGauge
extern void ui_srcEngineGauge_screen_init(void);
extern void ui_srcEngineGauge_screen_destroy(void);
extern lv_obj_t * ui_srcEngineGauge;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Gauge1;
extern lv_obj_t * ui_arcWaterTempIn;
extern lv_obj_t * ui_txtWaterTempIn;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Gauge2;
extern lv_obj_t * ui_arcWaterTempIn1;
extern lv_obj_t * ui_txtWaterTempOutlet;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Gauge3;
extern lv_obj_t * ui_arcWaterFlowRate;
extern lv_obj_t * ui_txtWaterFlowRate;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Gauge4;
extern lv_obj_t * ui_arcEngineRpm;
extern lv_obj_t * ui_txtEngineRpm;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Gauge5;
extern lv_obj_t * ui_arcAirTempIntake;
extern lv_obj_t * ui_txtAirTempIntake;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Gauge6;
extern lv_obj_t * ui_arcAirTempExhaust;
extern lv_obj_t * ui_txtAirTempExhaust;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Gauge7;
extern lv_obj_t * ui_arcAirFlowIntake;
extern lv_obj_t * ui_txtAirFlowIntake;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Gauge8;
extern lv_obj_t * ui_arcAirFlowExhaust;
extern lv_obj_t * ui_txtAirFlowExhaust;
extern lv_obj_t * ui_Label15;
extern void ui_event_btnBack(lv_event_t * e);
extern lv_obj_t * ui_btnBack;
extern lv_obj_t * ui_Label17;
extern void ui_event_btnNext(lv_event_t * e);
extern lv_obj_t * ui_btnNext;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES
extern lv_obj_t * uic_arcWaterTempIn;
extern lv_obj_t * uic_txtWaterTempIn;
extern lv_obj_t * uic_txtWaterTempOutlet;
extern lv_obj_t * uic_arcWaterFlowRate;
extern lv_obj_t * uic_txtWaterFlowRate;
extern lv_obj_t * uic_arcEngineRpm;
extern lv_obj_t * uic_txtEngineRpm;
extern lv_obj_t * uic_arcAirTempIntake;
extern lv_obj_t * uic_txtAirTempIntake;
extern lv_obj_t * uic_arcAirTempExhaust;
extern lv_obj_t * uic_txtAirTempExhaust;
extern lv_obj_t * uic_arcAirFlowIntake;
extern lv_obj_t * uic_txtAirFlowIntake;
extern lv_obj_t * uic_arcAirFlowExhaust;
extern lv_obj_t * uic_txtAirFlowExhaust;
extern lv_obj_t * uic_btnBack;
extern lv_obj_t * uic_btnNext;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

