// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BSU_Engine_Gauge

#include "ui.h"

lv_obj_t * uic_btnLoadTesting;
lv_obj_t * uic_btnGeneratorGauge;
lv_obj_t * uic_btnEngineGauge;
lv_obj_t * uic_scrMain;
lv_obj_t * ui_scrMain = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btnEngineGauge = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_btnGeneratorGauge = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_btnLoadTesting = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_btnEngineGauge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_srcEngineGauge, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_srcEngineGauge_screen_init);
    }
}

// build funtions

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 35);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "BATANGAS STATE UNIVERSITY");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 90);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "THE PHILIPPINES' NATIONAL ENGINEERING UNIVERSITY");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_Image1, &ui_img_logo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Image1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 153);
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "ENGINE AND GENERATOR TESTING APPARATUS");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnEngineGauge = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btnEngineGauge, 300);
    lv_obj_set_height(ui_btnEngineGauge, 120);
    lv_obj_set_x(ui_btnEngineGauge, -250);
    lv_obj_set_y(ui_btnEngineGauge, 25);
    lv_obj_set_align(ui_btnEngineGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnEngineGauge, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnEngineGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_btnEngineGauge);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "ENGINE\nGAUGES");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnGeneratorGauge = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btnGeneratorGauge, 300);
    lv_obj_set_height(ui_btnGeneratorGauge, 120);
    lv_obj_set_x(ui_btnGeneratorGauge, 250);
    lv_obj_set_y(ui_btnGeneratorGauge, 25);
    lv_obj_set_align(ui_btnGeneratorGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGeneratorGauge, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnGeneratorGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_btnGeneratorGauge);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "GENERATOR\nGAUGES");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnLoadTesting = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btnLoadTesting, 300);
    lv_obj_set_height(ui_btnLoadTesting, 120);
    lv_obj_set_x(ui_btnLoadTesting, 0);
    lv_obj_set_y(ui_btnLoadTesting, 180);
    lv_obj_set_align(ui_btnLoadTesting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnLoadTesting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnLoadTesting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_btnLoadTesting);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "LOAD\nTESTING");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnEngineGauge, ui_event_btnEngineGauge, LV_EVENT_ALL, NULL);
    uic_scrMain = ui_scrMain;
    uic_btnEngineGauge = ui_btnEngineGauge;
    uic_btnGeneratorGauge = ui_btnGeneratorGauge;
    uic_btnLoadTesting = ui_btnLoadTesting;

}

void ui_scrMain_screen_destroy(void)
{
    if(ui_scrMain) lv_obj_del(ui_scrMain);

    // NULL screen variables
    uic_scrMain = NULL;
    ui_scrMain = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Image1 = NULL;
    ui_Label3 = NULL;
    uic_btnEngineGauge = NULL;
    ui_btnEngineGauge = NULL;
    ui_Label4 = NULL;
    uic_btnGeneratorGauge = NULL;
    ui_btnGeneratorGauge = NULL;
    ui_Label5 = NULL;
    uic_btnLoadTesting = NULL;
    ui_btnLoadTesting = NULL;
    ui_Label6 = NULL;

}
