// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BSU_Engine_Gauge

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label3;
extern void ui_event_btnEngineGauge(lv_event_t * e);
extern lv_obj_t * ui_btnEngineGauge;
extern lv_obj_t * ui_Label4;
extern void ui_event_btnGeneratorGauge(lv_event_t * e);
extern lv_obj_t * ui_btnGeneratorGauge;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrMain;
extern lv_obj_t * uic_btnEngineGauge;
extern lv_obj_t * uic_btnGeneratorGauge;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

