// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BSU_Engine_Gauge

#include "ui.h"

lv_obj_t * uic_btnNext;
lv_obj_t * uic_btnBack;
lv_obj_t * uic_txtAirFlowExhaust;
lv_obj_t * uic_arcAirFlowExhaust;
lv_obj_t * uic_txtAirFlowIntake;
lv_obj_t * uic_arcAirFlowIntake;
lv_obj_t * uic_txtAirTempExhaust;
lv_obj_t * uic_arcAirTempExhaust;
lv_obj_t * uic_txtAirTempIntake;
lv_obj_t * uic_arcAirTempIntake;
lv_obj_t * uic_txtEngineRpm;
lv_obj_t * uic_arcEngineRpm;
lv_obj_t * uic_txtWaterFlowRate;
lv_obj_t * uic_arcWaterFlowRate;
lv_obj_t * uic_txtWaterTempOutlet;
lv_obj_t * uic_txtWaterTempIn;
lv_obj_t * uic_arcWaterTempIn;
lv_obj_t * ui_srcEngineGauge = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Gauge1 = NULL;
lv_obj_t * ui_arcWaterTempIn = NULL;
lv_obj_t * ui_txtWaterTempIn = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Gauge2 = NULL;
lv_obj_t * ui_arcWaterTempIn1 = NULL;
lv_obj_t * ui_txtWaterTempOutlet = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Gauge3 = NULL;
lv_obj_t * ui_arcWaterFlowRate = NULL;
lv_obj_t * ui_txtWaterFlowRate = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Gauge4 = NULL;
lv_obj_t * ui_arcEngineRpm = NULL;
lv_obj_t * ui_txtEngineRpm = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Gauge5 = NULL;
lv_obj_t * ui_arcAirTempIntake = NULL;
lv_obj_t * ui_txtAirTempIntake = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Gauge6 = NULL;
lv_obj_t * ui_arcAirTempExhaust = NULL;
lv_obj_t * ui_txtAirTempExhaust = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Gauge7 = NULL;
lv_obj_t * ui_arcAirFlowIntake = NULL;
lv_obj_t * ui_txtAirFlowIntake = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Gauge8 = NULL;
lv_obj_t * ui_arcAirFlowExhaust = NULL;
lv_obj_t * ui_txtAirFlowExhaust = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_btnBack = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_btnNext = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions

// build funtions

void ui_srcEngineGauge_screen_init(void)
{
    ui_srcEngineGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_srcEngineGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_srcEngineGauge);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 35);
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "ENGINE GAUGES");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_srcEngineGauge);
    lv_img_set_src(ui_Image2, &ui_img_logo_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Image2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge1 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge1);
    lv_obj_set_width(ui_Gauge1, 200);
    lv_obj_set_height(ui_Gauge1, 200);
    lv_obj_set_x(ui_Gauge1, -350);
    lv_obj_set_y(ui_Gauge1, -95);
    lv_obj_set_align(ui_Gauge1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge1, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge1, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge1, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcWaterTempIn = lv_arc_create(ui_Gauge1);
    lv_obj_set_width(ui_arcWaterTempIn, 135);
    lv_obj_set_height(ui_arcWaterTempIn, 135);
    lv_obj_set_align(ui_arcWaterTempIn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcWaterTempIn, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcWaterTempIn, 50);
    lv_obj_set_style_arc_color(ui_arcWaterTempIn, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcWaterTempIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWaterTempIn, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWaterTempIn, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtWaterTempIn = lv_label_create(ui_Gauge1);
    lv_obj_set_width(ui_txtWaterTempIn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtWaterTempIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtWaterTempIn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtWaterTempIn, "20 C");
    lv_obj_set_style_text_font(ui_txtWaterTempIn, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Gauge1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 1);
    lv_obj_set_y(ui_Label11, 61);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "INLET\nWATER TEMP");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge2 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge2);
    lv_obj_set_width(ui_Gauge2, 200);
    lv_obj_set_height(ui_Gauge2, 200);
    lv_obj_set_x(ui_Gauge2, -120);
    lv_obj_set_y(ui_Gauge2, -95);
    lv_obj_set_align(ui_Gauge2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge2, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge2, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge2, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcWaterTempIn1 = lv_arc_create(ui_Gauge2);
    lv_obj_set_width(ui_arcWaterTempIn1, 135);
    lv_obj_set_height(ui_arcWaterTempIn1, 135);
    lv_obj_set_align(ui_arcWaterTempIn1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcWaterTempIn1, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcWaterTempIn1, 50);
    lv_obj_set_style_arc_color(ui_arcWaterTempIn1, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcWaterTempIn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWaterTempIn1, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWaterTempIn1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtWaterTempOutlet = lv_label_create(ui_Gauge2);
    lv_obj_set_width(ui_txtWaterTempOutlet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtWaterTempOutlet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtWaterTempOutlet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtWaterTempOutlet, "20 C");
    lv_obj_set_style_text_font(ui_txtWaterTempOutlet, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Gauge2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 1);
    lv_obj_set_y(ui_Label8, 61);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "OUTLET\nWATER TEMP");
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge3 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge3);
    lv_obj_set_width(ui_Gauge3, 200);
    lv_obj_set_height(ui_Gauge3, 200);
    lv_obj_set_x(ui_Gauge3, 120);
    lv_obj_set_y(ui_Gauge3, -95);
    lv_obj_set_align(ui_Gauge3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge3, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge3, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge3, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcWaterFlowRate = lv_arc_create(ui_Gauge3);
    lv_obj_set_width(ui_arcWaterFlowRate, 135);
    lv_obj_set_height(ui_arcWaterFlowRate, 135);
    lv_obj_set_align(ui_arcWaterFlowRate, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcWaterFlowRate, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcWaterFlowRate, 50);
    lv_obj_set_style_arc_color(ui_arcWaterFlowRate, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcWaterFlowRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcWaterFlowRate, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcWaterFlowRate, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtWaterFlowRate = lv_label_create(ui_Gauge3);
    lv_obj_set_width(ui_txtWaterFlowRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtWaterFlowRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtWaterFlowRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtWaterFlowRate, "4 L/S");
    lv_obj_set_style_text_font(ui_txtWaterFlowRate, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Gauge3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 1);
    lv_obj_set_y(ui_Label9, 61);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "FLOWRATE\nWATER TEMP");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge4 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge4);
    lv_obj_set_width(ui_Gauge4, 200);
    lv_obj_set_height(ui_Gauge4, 200);
    lv_obj_set_x(ui_Gauge4, 350);
    lv_obj_set_y(ui_Gauge4, -95);
    lv_obj_set_align(ui_Gauge4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge4, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge4, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge4, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcEngineRpm = lv_arc_create(ui_Gauge4);
    lv_obj_set_width(ui_arcEngineRpm, 135);
    lv_obj_set_height(ui_arcEngineRpm, 135);
    lv_obj_set_align(ui_arcEngineRpm, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcEngineRpm, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcEngineRpm, 50);
    lv_obj_set_style_arc_color(ui_arcEngineRpm, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcEngineRpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcEngineRpm, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcEngineRpm, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtEngineRpm = lv_label_create(ui_Gauge4);
    lv_obj_set_width(ui_txtEngineRpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtEngineRpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtEngineRpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtEngineRpm, "1500");
    lv_obj_set_style_text_font(ui_txtEngineRpm, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Gauge4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 1);
    lv_obj_set_y(ui_Label10, 61);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "ENGINE\nRPM");
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge5 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge5);
    lv_obj_set_width(ui_Gauge5, 200);
    lv_obj_set_height(ui_Gauge5, 200);
    lv_obj_set_x(ui_Gauge5, -350);
    lv_obj_set_y(ui_Gauge5, 150);
    lv_obj_set_align(ui_Gauge5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge5, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge5, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge5, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcAirTempIntake = lv_arc_create(ui_Gauge5);
    lv_obj_set_width(ui_arcAirTempIntake, 135);
    lv_obj_set_height(ui_arcAirTempIntake, 135);
    lv_obj_set_align(ui_arcAirTempIntake, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcAirTempIntake, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcAirTempIntake, 50);
    lv_obj_set_style_arc_color(ui_arcAirTempIntake, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcAirTempIntake, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcAirTempIntake, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcAirTempIntake, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtAirTempIntake = lv_label_create(ui_Gauge5);
    lv_obj_set_width(ui_txtAirTempIntake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAirTempIntake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtAirTempIntake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAirTempIntake, "50 C");
    lv_obj_set_style_text_font(ui_txtAirTempIntake, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Gauge5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 1);
    lv_obj_set_y(ui_Label12, 61);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "INTAKE\nAIR TEMP");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge6 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge6);
    lv_obj_set_width(ui_Gauge6, 200);
    lv_obj_set_height(ui_Gauge6, 200);
    lv_obj_set_x(ui_Gauge6, -120);
    lv_obj_set_y(ui_Gauge6, 150);
    lv_obj_set_align(ui_Gauge6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge6, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge6, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge6, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcAirTempExhaust = lv_arc_create(ui_Gauge6);
    lv_obj_set_width(ui_arcAirTempExhaust, 135);
    lv_obj_set_height(ui_arcAirTempExhaust, 135);
    lv_obj_set_align(ui_arcAirTempExhaust, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcAirTempExhaust, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcAirTempExhaust, 50);
    lv_obj_set_style_arc_color(ui_arcAirTempExhaust, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcAirTempExhaust, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcAirTempExhaust, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcAirTempExhaust, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtAirTempExhaust = lv_label_create(ui_Gauge6);
    lv_obj_set_width(ui_txtAirTempExhaust, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAirTempExhaust, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtAirTempExhaust, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAirTempExhaust, "50 C");
    lv_obj_set_style_text_font(ui_txtAirTempExhaust, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Gauge6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 1);
    lv_obj_set_y(ui_Label13, 61);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "INTAKE\nAIR TEMP");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge7 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge7);
    lv_obj_set_width(ui_Gauge7, 200);
    lv_obj_set_height(ui_Gauge7, 200);
    lv_obj_set_x(ui_Gauge7, 120);
    lv_obj_set_y(ui_Gauge7, 150);
    lv_obj_set_align(ui_Gauge7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge7, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge7, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge7, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge7, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcAirFlowIntake = lv_arc_create(ui_Gauge7);
    lv_obj_set_width(ui_arcAirFlowIntake, 135);
    lv_obj_set_height(ui_arcAirFlowIntake, 135);
    lv_obj_set_align(ui_arcAirFlowIntake, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcAirFlowIntake, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcAirFlowIntake, 50);
    lv_obj_set_style_arc_color(ui_arcAirFlowIntake, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcAirFlowIntake, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcAirFlowIntake, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcAirFlowIntake, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtAirFlowIntake = lv_label_create(ui_Gauge7);
    lv_obj_set_width(ui_txtAirFlowIntake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAirFlowIntake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtAirFlowIntake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAirFlowIntake, "4 L/S");
    lv_obj_set_style_text_font(ui_txtAirFlowIntake, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Gauge7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 1);
    lv_obj_set_y(ui_Label14, 61);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "FLOW RATE\nAIR INTAKE");
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gauge8 = lv_obj_create(ui_srcEngineGauge);
    lv_obj_remove_style_all(ui_Gauge8);
    lv_obj_set_width(ui_Gauge8, 200);
    lv_obj_set_height(ui_Gauge8, 200);
    lv_obj_set_x(ui_Gauge8, 350);
    lv_obj_set_y(ui_Gauge8, 150);
    lv_obj_set_align(ui_Gauge8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Gauge8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gauge8, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gauge8, lv_color_hex(0xE0DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauge8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gauge8, lv_color_hex(0x961414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gauge8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Gauge8, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcAirFlowExhaust = lv_arc_create(ui_Gauge8);
    lv_obj_set_width(ui_arcAirFlowExhaust, 135);
    lv_obj_set_height(ui_arcAirFlowExhaust, 135);
    lv_obj_set_align(ui_arcAirFlowExhaust, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_arcAirFlowExhaust, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_arcAirFlowExhaust, 50);
    lv_obj_set_style_arc_color(ui_arcAirFlowExhaust, lv_color_hex(0xC21C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcAirFlowExhaust, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcAirFlowExhaust, lv_color_hex(0xDB1F1F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcAirFlowExhaust, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_txtAirFlowExhaust = lv_label_create(ui_Gauge8);
    lv_obj_set_width(ui_txtAirFlowExhaust, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAirFlowExhaust, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_txtAirFlowExhaust, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAirFlowExhaust, "4 L/S");
    lv_obj_set_style_text_font(ui_txtAirFlowExhaust, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Gauge8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 1);
    lv_obj_set_y(ui_Label15, 61);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "FLOW RATE\nAIR EXHAUST");
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack = lv_btn_create(ui_srcEngineGauge);
    lv_obj_set_width(ui_btnBack, 180);
    lv_obj_set_height(ui_btnBack, 60);
    lv_obj_set_x(ui_btnBack, -400);
    lv_obj_set_y(ui_btnBack, -250);
    lv_obj_set_align(ui_btnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_btnBack);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "BACK");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnNext = lv_btn_create(ui_srcEngineGauge);
    lv_obj_set_width(ui_btnNext, 180);
    lv_obj_set_height(ui_btnNext, 60);
    lv_obj_set_x(ui_btnNext, 400);
    lv_obj_set_y(ui_btnNext, -250);
    lv_obj_set_align(ui_btnNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_btnNext);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "NEXT");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_arcWaterTempIn = ui_arcWaterTempIn;
    uic_txtWaterTempIn = ui_txtWaterTempIn;
    uic_txtWaterTempOutlet = ui_txtWaterTempOutlet;
    uic_arcWaterFlowRate = ui_arcWaterFlowRate;
    uic_txtWaterFlowRate = ui_txtWaterFlowRate;
    uic_arcEngineRpm = ui_arcEngineRpm;
    uic_txtEngineRpm = ui_txtEngineRpm;
    uic_arcAirTempIntake = ui_arcAirTempIntake;
    uic_txtAirTempIntake = ui_txtAirTempIntake;
    uic_arcAirTempExhaust = ui_arcAirTempExhaust;
    uic_txtAirTempExhaust = ui_txtAirTempExhaust;
    uic_arcAirFlowIntake = ui_arcAirFlowIntake;
    uic_txtAirFlowIntake = ui_txtAirFlowIntake;
    uic_arcAirFlowExhaust = ui_arcAirFlowExhaust;
    uic_txtAirFlowExhaust = ui_txtAirFlowExhaust;
    uic_btnBack = ui_btnBack;
    uic_btnNext = ui_btnNext;

}

void ui_srcEngineGauge_screen_destroy(void)
{
    if(ui_srcEngineGauge) lv_obj_del(ui_srcEngineGauge);

    // NULL screen variables
    ui_srcEngineGauge = NULL;
    ui_Label7 = NULL;
    ui_Image2 = NULL;
    ui_Gauge1 = NULL;
    uic_arcWaterTempIn = NULL;
    ui_arcWaterTempIn = NULL;
    uic_txtWaterTempIn = NULL;
    ui_txtWaterTempIn = NULL;
    ui_Label11 = NULL;
    ui_Gauge2 = NULL;
    ui_arcWaterTempIn1 = NULL;
    uic_txtWaterTempOutlet = NULL;
    ui_txtWaterTempOutlet = NULL;
    ui_Label8 = NULL;
    ui_Gauge3 = NULL;
    uic_arcWaterFlowRate = NULL;
    ui_arcWaterFlowRate = NULL;
    uic_txtWaterFlowRate = NULL;
    ui_txtWaterFlowRate = NULL;
    ui_Label9 = NULL;
    ui_Gauge4 = NULL;
    uic_arcEngineRpm = NULL;
    ui_arcEngineRpm = NULL;
    uic_txtEngineRpm = NULL;
    ui_txtEngineRpm = NULL;
    ui_Label10 = NULL;
    ui_Gauge5 = NULL;
    uic_arcAirTempIntake = NULL;
    ui_arcAirTempIntake = NULL;
    uic_txtAirTempIntake = NULL;
    ui_txtAirTempIntake = NULL;
    ui_Label12 = NULL;
    ui_Gauge6 = NULL;
    uic_arcAirTempExhaust = NULL;
    ui_arcAirTempExhaust = NULL;
    uic_txtAirTempExhaust = NULL;
    ui_txtAirTempExhaust = NULL;
    ui_Label13 = NULL;
    ui_Gauge7 = NULL;
    uic_arcAirFlowIntake = NULL;
    ui_arcAirFlowIntake = NULL;
    uic_txtAirFlowIntake = NULL;
    ui_txtAirFlowIntake = NULL;
    ui_Label14 = NULL;
    ui_Gauge8 = NULL;
    uic_arcAirFlowExhaust = NULL;
    ui_arcAirFlowExhaust = NULL;
    uic_txtAirFlowExhaust = NULL;
    ui_txtAirFlowExhaust = NULL;
    ui_Label15 = NULL;
    uic_btnBack = NULL;
    ui_btnBack = NULL;
    ui_Label17 = NULL;
    uic_btnNext = NULL;
    ui_btnNext = NULL;
    ui_Label16 = NULL;

}
