// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BSU_Engine_Gauge

#ifndef UI_SRCGENERATORGAUGE_H
#define UI_SRCGENERATORGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_srcGeneratorGauge
extern void ui_srcGeneratorGauge_screen_init(void);
extern void ui_srcGeneratorGauge_screen_destroy(void);
extern lv_obj_t * ui_srcGeneratorGauge;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Gauge9;
extern lv_obj_t * ui_arcVoltage;
extern lv_obj_t * ui_txtVoltage;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Gauge10;
extern lv_obj_t * ui_arcAmpere;
extern lv_obj_t * ui_txtAmpere;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Gauge11;
extern lv_obj_t * ui_arcPower;
extern lv_obj_t * ui_txtPower;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Gauge12;
extern lv_obj_t * ui_arcEngineRpm1;
extern lv_obj_t * ui_txtEngineRpm1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Gauge14;
extern lv_obj_t * ui_arcLoadCell;
extern lv_obj_t * ui_txtLoadCell;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Gauge15;
extern lv_obj_t * ui_arcGasFlowRate;
extern lv_obj_t * ui_txtGasFlowRate;
extern lv_obj_t * ui_Label25;
extern void ui_event_btnBack1(lv_event_t * e);
extern lv_obj_t * ui_btnBack1;
extern lv_obj_t * ui_Label27;
extern void ui_event_btnNext1(lv_event_t * e);
extern lv_obj_t * ui_btnNext1;
extern lv_obj_t * ui_Label28;
// CUSTOM VARIABLES
extern lv_obj_t * uic_srcGeneratorGauge;
extern lv_obj_t * uic_arcVoltage;
extern lv_obj_t * uic_txtVoltage;
extern lv_obj_t * uic_arcAmpere;
extern lv_obj_t * uic_txtAmpere;
extern lv_obj_t * uic_arcPower;
extern lv_obj_t * uic_txtPower;
extern lv_obj_t * uic_arcEngineRpm1;
extern lv_obj_t * uic_txtEngineRpm1;
extern lv_obj_t * uic_arcLoadCell;
extern lv_obj_t * uic_txtLoadCell;
extern lv_obj_t * uic_arcGasFlowRate;
extern lv_obj_t * uic_txtGasFlowRate;
extern lv_obj_t * uic_btnBack1;
extern lv_obj_t * uic_btnNext1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

